In [1]:
print("hello")


hello


In [1]:
import numpy as np 

In [2]:
l = [1,2,3]
l

[1, 2, 3]

In [3]:
type(l)

list

In [4]:
np.array(l)

array([1, 2, 3])

In [5]:
type(l)

list

In [12]:
l = [[1,2,3],[3,4,5],[6,7,8]]
np.array(l)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
type(l)

list

In [14]:
l = np.array(l)

In [15]:
l

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
type(l)

numpy.ndarray

In [19]:
l

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
#array generatic fun 

In [22]:
l

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
l = np.arange(1,21)

In [24]:
l

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
l

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
l = [[1,2,3],[3,4,5],[6,7,8]]
np.array(l)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
l

[[1, 2, 3], [3, 4, 5], [6, 7, 8]]

In [29]:
l = np.array(l)
l

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
l = np.zeros(6)

In [36]:
l 

array([0., 0., 0., 0., 0., 0.])

In [37]:
l = np.ones(4)

In [38]:
l

array([1., 1., 1., 1.])

In [39]:
arr = np.arange(1,21,2)

In [40]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [46]:
arr =np.linspace(1,21,15)

In [47]:
arr

array([ 1.        ,  2.42857143,  3.85714286,  5.28571429,  6.71428571,
        8.14285714,  9.57142857, 11.        , 12.42857143, 13.85714286,
       15.28571429, 16.71428571, 18.14285714, 19.57142857, 21.        ])

In [50]:
arr = np.random.rand(21)

In [51]:
arr

array([0.73000245, 0.24436244, 0.93994063, 0.5363281 , 0.13161085,
       0.51710638, 0.70815585, 0.26956608, 0.5280788 , 0.22620354,
       0.89295439, 0.0662333 , 0.30483428, 0.25107637, 0.59158985,
       0.83577656, 0.35533175, 0.41644947, 0.58405059, 0.72870745,
       0.9591247 ])

In [55]:
arr = np.random.randn(21)
arr

array([ 6.57492593e-01, -1.52587020e+00, -7.17696828e-01, -3.42449065e-02,
       -1.30998044e+00, -5.59257002e-01,  5.22547500e-01,  6.21148700e-02,
       -1.22677231e+00,  4.75506029e-03,  1.26735808e+00, -1.37552658e+00,
        1.18288277e+00, -2.58532658e-01,  3.21287177e-04, -1.02296538e+00,
       -1.45365746e+00,  3.65055078e-01,  4.18051648e-01, -2.96232816e-01,
       -2.17138247e+00])

In [60]:
arr = np.random.randint(1000)
arr

450

In [71]:
np.random.randint(10,21,7)

array([15, 17, 11, 14, 19, 17, 17], dtype=int32)

In [72]:
## Array Attribute

In [73]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [76]:
num = np.arange(1,31,2)
num

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [79]:
num.size

15

In [80]:
num.shape

(15,)

In [84]:
l = np.array([[1,2,3],[4,5,6],[7,8,9]])
l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
l.sum().item()

45

In [90]:
l.size

9

In [91]:
l.shape

(3, 3)

In [95]:
l.dtype

'int64'

In [97]:
l.min()

np.int64(1)

In [98]:
l.max()

np.int64(9)

In [99]:
l.mean()

np.float64(5.0)

In [100]:
l.std()

np.float64(2.581988897471611)

In [101]:
l.argmax()

np.int64(8)

In [102]:
l.argmin()

np.int64(0)

In [105]:
l.mT

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [106]:
l.sum(axis=1)

array([ 6, 15, 24])

In [107]:
l.sum(axis=0)

array([12, 15, 18])

In [109]:
l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
num = np.arange(1,31)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [113]:
num.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [114]:
num = np.arange(1,51,2).reshape(5,5)
num

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [115]:
num.size

25

In [116]:
num.shape

(5, 5)

In [117]:
num.mean()

np.float64(25.0)

In [118]:
num.std()

np.float64(14.422205101855956)

In [119]:
## array indexing

In [120]:
num

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [124]:
num[1][4].item()

19

In [126]:
num[0,4]

np.int64(9)

In [127]:
num[::,2]

array([ 5, 15, 25, 35, 45])

In [128]:
num[0:5,0:2]

array([[ 1,  3],
       [11, 13],
       [21, 23],
       [31, 33],
       [41, 43]])

In [129]:
num[2:4,2:4]

array([[25, 27],
       [35, 37]])

In [138]:
num[::,4]

array([ 9, 19, 29, 39, 49])

In [136]:
num

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [141]:
for i in num:
    print(i*2)

[ 2  6 10 14 18]
[22 26 30 34 38]
[42 46 50 54 58]
[62 66 70 74 78]
[82 86 90 94 98]


In [142]:
for i in num:
    print(i % 2 == 0)

[False False False False False]
[False False False False False]
[False False False False False]
[False False False False False]
[False False False False False]


In [144]:
n = np.arange(1,31).reshape(6,5)
n

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [145]:
for i in n:
    print(i % 2 == 0)

[False  True False  True False]
[ True False  True False  True]
[False  True False  True False]
[ True False  True False  True]
[False  True False  True False]
[ True False  True False  True]


In [150]:
array_slice = i % 2 == 0

In [151]:
array_slice

array([ True, False,  True, False,  True])

In [154]:
arr2 = n[5][3]=6
arr2

6

In [155]:
arr2

6

In [156]:
n

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28,  6, 30]])

In [166]:
c = n 
c = n

In [167]:
n

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28,  6, 30]])

In [168]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28,  6, 30]])

In [169]:
c[0][0] = 67 
c

array([[67,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28,  6, 30]])

In [170]:
n

array([[67,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28,  6, 30]])

In [171]:
c = n.copy() 
c[0][0] = 98 
c

array([[98,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28,  6, 30]])

In [172]:
n

array([[67,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28,  6, 30]])

In [183]:
#  operation 

In [175]:
n = np.array([1,2,3,4])
a = np.array([5,6,7,8])
n + a

array([ 6,  8, 10, 12])

In [176]:
arr = n-a

In [177]:
arr

array([-4, -4, -4, -4])

In [178]:
arr = n*a

In [179]:
arr

array([ 5, 12, 21, 32])

In [180]:
n // a

array([0, 0, 0, 0])

In [181]:
n ** a

array([    1,    64,  2187, 65536])

In [182]:
n/a

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [184]:
n == a

array([False, False, False, False])

In [185]:
n != a

array([ True,  True,  True,  True])

In [186]:
num

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [188]:
n 

array([1, 2, 3, 4])

In [189]:
a

array([5, 6, 7, 8])

In [191]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [192]:
 n @ a

np.int64(70)

In [193]:
a

array([5, 6, 7, 8])

In [194]:
A

array([[1, 2],
       [3, 4]])

In [195]:
B

array([[5, 6],
       [7, 8]])

In [196]:
A @ B

array([[19, 22],
       [43, 50]])

In [199]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [200]:
A.T

array([[1, 3],
       [2, 4]])

In [201]:
a

array([5, 6, 7, 8])

In [202]:
n

array([1, 2, 3, 4])

In [204]:
np.vstack((a,n))

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [205]:
n = np.array([1,2,3,4])
a = np.array([5,6,7,8])

In [206]:
np.hstack((n,a))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [208]:
np.column_stack((n,a))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [209]:
num

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [212]:
np.vsplit(num,5)

[array([[1, 3, 5, 7, 9]]),
 array([[11, 13, 15, 17, 19]]),
 array([[21, 23, 25, 27, 29]]),
 array([[31, 33, 35, 37, 39]]),
 array([[41, 43, 45, 47, 49]])]

In [213]:
np.hsplit(num,5)

[array([[ 1],
        [11],
        [21],
        [31],
        [41]]),
 array([[ 3],
        [13],
        [23],
        [33],
        [43]]),
 array([[ 5],
        [15],
        [25],
        [35],
        [45]]),
 array([[ 7],
        [17],
        [27],
        [37],
        [47]]),
 array([[ 9],
        [19],
        [29],
        [39],
        [49]])]

In [214]:
n = np.arange(16).reshape(4,4)

In [215]:
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [216]:
np.hsplit(n,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [218]:
np.hsplit(n,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [219]:
np.vsplit(n,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [221]:
np.hsplit(n,1)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [222]:
np.hsplit(n,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]