In [2]:
print("Numpy")

Numpy


In [1]:
import numpy as np 

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
a =[1,2,3,4.5 ]
a

[1, 2, 3, 4.5]

In [6]:
np.array(a)

array([1. , 2. , 3. , 4.5])

In [1]:
array = [1,2,3,4]
print(array)

[1, 2, 3, 4]


In [17]:
l = [[1,2,3],[1,2,3],[4,5,6]]
l

[[1, 2, 3], [1, 2, 3], [4, 5, 6]]

In [18]:
type(l)

list

In [19]:
import numpy as np
np.array(l)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [20]:
type(l)

list

In [6]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [7]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [11]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
arr = np.linspace(1,5,2)
arr

array([1., 5.])

In [17]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [18]:
arr = np.linspace(1,10,100)
arr

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [20]:
np.random.rand(10)

array([0.77988432, 0.78042612, 0.05727918, 0.64674135, 0.1660561 ,
       0.04793199, 0.12443865, 0.69832451, 0.99922397, 0.17475391])

In [21]:
np.random.randn(10)

array([-1.52725226, -0.35820207,  0.78584679, -0.88484133,  0.94308999,
        0.15156294,  0.51383241, -1.12356425, -1.3619307 ,  0.33157462])

In [25]:
np.random.randint(10,20,10)

array([15, 16, 11, 16, 10, 10, 13, 17, 18, 16], dtype=int32)

## Array Attribute

In [26]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr.shape  # row and column

(3, 3)

In [28]:
arr.size

9

In [29]:
arr.dtype

dtype('int64')

Array method

In [30]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr.min()  # int(arr.min()) also you can use

np.int64(1)

In [35]:
int(arr.max())

9

In [37]:
int(arr.sum())

45

In [38]:
arr.sum()

np.int64(45)

In [39]:
np.sum(arr,axis=0)  # row wise = 1 and column wise = 0 

array([12, 15, 18])

In [40]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [41]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr.mean()

np.float64(5.0)

In [44]:
arr.mean()

np.float64(5.0)

In [45]:
arr.std()  

np.float64(2.581988897471611)

In [46]:
arr.argmax()   # highest value in arr ka index

np.int64(8)

In [47]:
arr.argmin()

np.int64(0)

Reshaping and resizing

In [48]:
import numpy as np

In [50]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [53]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

##Array indexing

In [56]:
arr  = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [59]:
arr[9].item()

20

In [60]:
arr[1:5]

array([12, 13, 14, 15])

In [61]:
arr[:5]

array([11, 12, 13, 14, 15])

In [62]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [63]:
arr[0:9:2]

array([11, 13, 15, 17, 19])

In [67]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [66]:
arr[4].item()

15

## NUMPY INDEXING AND SLICING OF MATRIX

In [70]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [71]:
arr[0]

array([1, 2, 3, 4, 5])

In [72]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [73]:
arr[5]

array([26, 27, 28, 29, 30])

In [75]:
arr[5][2].item()

28

In [76]:
arr[0,0]

np.int64(1)

In [78]:
arr[5,4].item()

30

In [79]:
arr[0:2,1:3]    ## first mai row hai sling or dusre mai column for scling 

array([[2, 3],
       [7, 8]])

In [80]:
arr[3:6,3:6]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [81]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [82]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [86]:
arr[:,0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18],
       [21, 22, 23],
       [26, 27, 28]])

In [87]:
arr[:,0:3:2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23],
       [26, 28]])

## Boolean indexing

In [8]:
import numpy as np
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [10]:
arr = arr[bool_index]      # sign convebtion
arr

array([12, 14, 16, 18, 20])

## Arrary operation

In [11]:
# ArthmArithmetic operatiom

In [14]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])


In [15]:
arr2 = a1 +a2  # size must be same as both array

array([ 7,  9, 11, 13, 15])

In [16]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [17]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [18]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [19]:
a1 // a2

array([0, 0, 0, 0, 0])

In [20]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [21]:
## Broadcasting

In [22]:
l = [10,20 ,30,40]
arr=np.array(l)

In [23]:
l + 10

TypeError: can only concatenate list (not "int") to list

In [24]:
for i in l:
    print(i + 10 )

20
30
40
50


In [25]:
arr + 10

array([20, 30, 40, 50])

In [27]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [29]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
arr2 = arr2+10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [31]:
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [32]:
arr2 * 10


array([[110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250],
       [260, 270, 280, 290, 300],
       [310, 320, 330, 340, 350]])

In [33]:
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [34]:
arr2 = arr2 *10
arr2

array([[110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250],
       [260, 270, 280, 290, 300],
       [310, 320, 330, 340, 350]])

In [ ]:
#Deep and shallow copy 

In [36]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
slice = a[:5]
slice*10

array([10, 20, 30, 40, 50])

In [41]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [47]:
lst = [1,2,3,4,5,6,7]
lst = lst[:4] * 10




In [48]:
lst

[1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4]

In [49]:
a[4:6]*10

array([50, 60])

In [50]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [52]:
a
c = a
c[0] = 99  # a ke andar bhi change hoga array m 

In [53]:
c

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [54]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [57]:
a
c = a.copy()  # ab copy hoga a m change nhi hoga
c[0] = 50

In [58]:
c

array([50,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [59]:
a         # a mai change nhi hua

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

## Matrix operation

In [62]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [63]:
A

array([[1, 2],
       [3, 4]])

In [64]:
B

array([[5, 6],
       [7, 8]])

In [65]:
A *B # not a matrixx matiple 

array([[ 5, 12],
       [21, 32]])

In [66]:
A @ B    # this is matrix matiplication

array([[19, 22],
       [43, 50]])

In [67]:
np.dot(A,B)   # matrix matipllication aslod denote this

array([[19, 22],
       [43, 50]])

In [68]:
A

array([[1, 2],
       [3, 4]])

In [69]:
A.T

array([[1, 3],
       [2, 4]])

In [70]:
#Stacking Array

In [71]:
A

array([[1, 2],
       [3, 4]])

In [72]:
B

array([[5, 6],
       [7, 8]])

In [73]:
# you cant stack to array already array hai 


In [74]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])


In [75]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [76]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [77]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [78]:
# split array

In [82]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [85]:
np.hsplit(c,3)  # you dont split 4 elements into 3 parts so its error shown

ValueError: array split does not result in an equal division

In [86]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [87]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [90]:
a = np.vsplit(c,4) 
a                    # 3 ka error hoga

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [91]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]


## Numpy Exericse